header:
  - name: Collections
    url: https://opentermsarchive.org/fr/collections/
    weight: 1
  - name: Mémos
    url: https://opentermsarchive.org/fr/memos/
    weight: 2
  - name: Documentation
    url: /fr
    weight: 3
  - name: Impact
    url: https://opentermsarchive.org/fr/impact/
    weight: 4
  - name: À propos
    url: https://opentermsarchive.org/fr/a-propos/
    weight: 5
footer:
  - name: Accueil
    url: https://opentermsarchive.org
    weight: 1
  - name: Collections
    url: https://opentermsarchive.org/fr/collections/
    weight: 2
  - name: Jeux de données
    url: https://opentermsarchive.org/fr/jeux-de-donnees/
    weight: 3
  - name: Mémos
    url: https://opentermsarchive.org/fr/memos/
    weight: 4
  - name: Documentation
    url: /fr
    weight: 5
  - name: Impact
    url: https://opentermsarchive.org/fr/impact/
    weight: 6
  - name: À propos
    url: https://opentermsarchive.org/fr/a-propos/
    weight: 7
first_subfooter:
  - name: État des services
    url: https://stats.uptimerobot.com/nXvrBcl0wx
    weight: 1
    params:
      target: _blank
  - name: Statistiques
    url: https://opentermsarchive.org/fr/statistiques/
    weight: 2
  - name: Média
    url: https://opentermsarchive.org/fr/media/
    weight: 3
  - name: Code source
    url: https://github.com/OpenTermsArchive
    weight: 4
    params:
      target: _blank
second_subfooter:
  - name: Mentions légales
    url: https://opentermsarchive.org/fr/mentions-legales/
    weight: 1
  - name: Politique de confidentialité
    url: https://opentermsarchive.org/fr/politique-de-confidentialite/
    weight: 2
  - name: 'Accessibilité : non conforme'
    url: https://opentermsarchive.org/fr/accessibilite/
    weight: 3
