github:
  url: https://github.com/OpenTermsArchive
mastodon: 
  url: https://mastodon.lescommuns.org/@opentermsarchive
  username: "@opentermsarchive@mastodon.lescommuns.org"
email: contact@opentermsarchive.org
